# Generated by Django 5.0.6 on 2024-07-07 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField()),
                ("profile_image", models.ImageField(upload_to="images")),
                ("department", models.CharField(max_length=255)),
                ("faculty", models.CharField(max_length=225)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField()),
                ("profile_image", models.ImageField(upload_to="images")),
                ("department", models.CharField(max_length=255)),
                ("faculty", models.CharField(max_length=225)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100 Level", "100 Level"),
                            ("200 Level", "200 Level"),
                            ("300 Level", "300 Level"),
                            ("400 Level", "400 Level"),
                            ("500 Level", "500 Level"),
                            ("600 Level", "600 Level"),
                            ("700 Level", "700 Level"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
