# Generated by Django 5.0.6 on 2024-07-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_lectureprofile_studentprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lectureprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lectureprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
