# Generated by Django 5.0.6 on 2024-07-08 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_lectureprofile_bio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LecturerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
                ("department", models.CharField(max_length=255)),
                ("faculty", models.CharField(max_length=225)),
                ("title", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="LectureProfile",
        ),
    ]
