# Generated by Django 5.0.6 on 2024-07-09 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_lecturerprofile_delete_lectureprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lecturerprofile",
            options={"verbose_name": "Lecturer Profile"},
        ),
        migrations.AlterModelOptions(
            name="studentprofile",
            options={"verbose_name": "Student Profile"},
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="graduation_year",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 9, 17, 12, 44, 143726)
            ),
        ),
    ]
