# Generated by Django 5.0.6 on 2024-07-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_lecturerprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="graduation_year",
            field=models.DateField(),
        ),
    ]
