# Generated by Django 5.0.6 on 2024-07-14 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_studentprofile_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_entry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=225)),
                ('bio', models.TextField(blank=True, null=True)),
                ('unique_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
