# Generated by Django 5.0.6 on 2024-07-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_studentprofile_year_of_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='faculty',
        ),
    ]
