# Generated by Django 5.0.6 on 2024-07-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_normaluser_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'Normal User Profile'},
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
