# Generated by Django 5.0.6 on 2024-07-17 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_normaluser_options_lecturerprofile_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='unique_id',
            field=models.UUIDField(
                blank=True, null=True, unique=True, default=uuid.uuid4, editable=True),
        ),
    ]
