# Generated by Django 5.0.6 on 2024-07-17 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_normaluser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='unique_id',
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
