# Generated by Django 5.0.6 on 2024-07-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_normaluser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
