# Generated by Django 5.0.6 on 2024-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_lecturerprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
