# Generated by Django 5.0.6 on 2024-08-01 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_normaluser_unique_id_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
